FROM rust:alpine
WORKDIR /usr/workdir/src/updater
COPY . .

RUN apk update && apk add --no-cache --purge \
    openssl-dev \
    openssl-libs-static \
    musl-dev \
    libc-dev \
    dcron

RUN cargo install --profile release --target x86_64-unknown-linux-musl --path .

RUN which updater || echo "Binary not in PATH!"

COPY run_updater.sh /usr/local/bin/run_updater.sh
COPY startup.sh /usr/local/bin/startup.sh
RUN chmod +x /usr/local/bin/run_updater.sh /usr/local/bin/startup.sh

RUN echo '0 1 * * * root /usr/local/bin/run_updater.sh' > /etc/crontabs/root && \
    chmod 0644 /etc/crontabs/root

CMD ["/usr/local/bin/startup.sh"]
